name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      # 檢出代碼
      - name: Check out code
        uses: actions/checkout@v1

      # 安裝 Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16

      # 構建和發布應用
      - name: Electron Builder Action
        uses: Yan-Jobs/action-electron-builder@v1.7.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}